title: Adunanza  # Name of the site
author:
  name: adunanza.net
metadata:
    description: 'Il portale ufficiale di Adunanza'

# TopBar
logo:
  icon: logo
  text: Adunanza
  url: "http://www.adunanza.net/"

# User Panel
userlinks:
    - text: Sample link
      url: "#"
    - text: Another Sample link
      url: "#"

# Header customization
header:
  title: Portale ufficiale
  description: Chi siamo, <em>i progetti </em>, <a href="http://forum.adunanza.net/" class="jumbolink">il forum</a> e <a href="https://discordapp.com/invite/0pfzTOXuEjt9ifvF" class="jumbolink">la chat.</a>.
  buttons:
    - text: "Iscriviti"
      url: "http://forum.adunanza.net/"
      icon: "user"

# Footer customization
footer:
  links:
    - text: Termini di servizio
      url: "http://forum.adunanza.net/tos"
    - text: Privacy
      url: "http://forum.adunanza.net/privacy"

#Social Count
socialcount:
    url: "http://forum.adunanza.net/"
    facebook_url: "https://www.facebook.com/pages/AdunanzA-P2P/199805353386088"
    twitter_url: "https://twitter.com/aduteam"

#Copyright
copyright: adunanza.net 2016.
